### ISSUE TITLE
More ASCII Art

### ISSUE THREAD

**Issue by jrtechs** [jrtechs/bash_manager#13]
Add more ascii art to the bash manager in the src/asciiArt folder. Ideally all the ascii art should be between 5-15 characters high.

**Comment by IngridGdesigns** [comment]
I want to work on this issue!

**Comment by jrtechs** [comment]
@IngridGdesigns sweet! Just make sure that you follow the format of the other files in the ascii directory.  👍

**Comment by zard777** [comment]
Hello guys, I think it would be more lovely if we had a wolf, whale, and shark join this Noah's Ark. 
Please review PR #28  :) 
__________________
Have a nice weekend ☕

**Comment by tsevans** [comment]
Added hippo and skeleton in #33!

**Comment by jrtechs** [comment]
We did it :100: 

![missions](https://user-images.githubusercontent.com/13894625/68995983-0dd37300-0862-11ea-85f8-c684794a1edb.png)
