### ISSUE TITLE
Update Quotes command to specify ascii art

### ISSUE THREAD

**Issue by jrtechs** [jrtechs/bash_manager#14]
Refactor the quotes.py file to specify the ascii file to use.
ie:
```
//this will do a random ascii animal
quote hello
```

```
//this will use the ascii art in src/asciiArt/roo.txt
quote hello --roo
```

After this is done, the batsay.py and roosay.py can be removed from the repository.

**Comment by librarianmage** [comment]
Fixed?

**Comment by jrtechs** [comment]
@MathWhiz Yes this is fixed. Sorry, I didn't close this sooner. @MathWhiz you can work on other issues in this repository or other repositories of mine if you want.
