### ISSUE TITLE
Local Port Forwarding

### ISSUE THREAD

**Issue by jrtechs** [jrtechs/bash_manager#15]
Similar to the normal ssh connections, I want a sub menu that manages ssh local port forwards. Since ssh forwarding commands are rather lengthy to type, it would be nice to have this program store the common ones that are used.

Consider this command:
```
ssh -L 9000:localhost:5432 user@example.com
```
Will forward everything on your machine listening on localhost on port 9000 to the remote ssh connection on port 5432.

```
ssh -L 9000:imgur.com:80 user@example.com
```

This command will forward everything listening on your machine on port 9000 to imgur.com:80 via the ssh connection. After you execute that command, localhost:9000 will become imgur.

Things that should be done:

- [ ] Option to get to sub menu from main menu
- [ ] Mechanism to add new local forward configurations -- can be done in a text/json file or .ssh config file
- [ ] Way to select and remove forward configurations from file
- [ ] Way to select local forward and run the correct ssh command

**Comment by brkr0671** [comment]
#/usr/bin
#ssh -L 9000:localhost:5432 user@example.com

**Comment by brkr0671** [comment]
is it work

**Comment by jrtechs** [comment]
@brkr0671 Thank you so much for looking at this. I will look at your PR tomorrow.
