### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by jrtechs** [jrtechs/bash_manager#16]
Since the readme was initially created a bunch of things were added to this project. It would be nice to update the readme to explain everything. Rather than using the text grabs of the script running, it should use screenshots since it would look a lot nicer.

**Comment by prasad-kumkar** [comment]
Sure, Let me give it a try :)

**Comment by jrtechs** [comment]
closed in #40

**Comment by PraizChrist** [comment]
how can I update readme

**Comment by jrtechs** [comment]
Sorry @PraizChrist,   this issue was closed with pr: https://github.com/jrtechs/bash_manager/pull/40

If you want to contribute to this repo, feel free to check out the other open issues.
