### ISSUE TITLE
Add Useful sh files to the scripts folder

### ISSUE THREAD

**Issue by jrtechs** [jrtechs/bash_manager#4]
Currently in my scripts folder I only have 1 script which optimizes images for websites.

I would like people to add their useful bash scripts to this folder.

**Comment by LiamBailey** [comment]
HI - I have a shell script that downloads the latest version of Wordpress from SVN and then creates it as a Docker instance - taking arguments for project name etc. Should I add it?

**Comment by jrtechs** [comment]
@LiamBailey Go for it! That sounds like something I might use.
