### ISSUE TITLE
Remove ASCII Art that is too large

### ISSUE THREAD

**Issue by jrtechs** [jrtechs/bash_manager#41]
Remove ASCII art in src/aciiArt that is taller that 14 lines.
Desired ascii art should be between [4, 14] line long.
Acii art that is any larger is hard to view in a standard terminal.

**Comment by RadientBrain** [comment]
Can I work on this? If yes then please assign it to me.

**Also please tell whether you want to permanently delete those arts which are greater than 14 lines or you want to create an archived art file that can later be enhanced by decreasing their sizes**

**Comment by RadientBrain** [comment]
Btw, I have made a **PR** according to your need and with some enhancements. ***Please merge it if you find it helpful!***
You can find it at #43.
Also if any other help is required please tell me. I will be more than happy to help you.

**Comment by jrtechs** [comment]
@RadientBrain  Thanks for working on this. If you are interested in working on this project more, feel free to look at the other issues on this repository. Feel free to comment and ask me if anything doesn't make sense.
