### ISSUE TITLE
New Acii Art

### ISSUE THREAD

**Issue by jrtechs** [jrtechs/bash_manager#42]
Create new ASCII art for this terminal-based quotes manager. Desired ASCII art should be between [0. 14] lines long and should have tick marks leading out to the mouth to a speech bubble.  A good example is: 
https://github.com/jrtechs/bash_manager/blob/master/src/asciiArt/dolphin.txt

**Comment by mbartlet** [comment]
Hello I'd be willing to work on this

**Comment by mbartlet** [comment]
PS I was able to find this through the Hacktoberfest label with https://hacktoberfest-finder.netlify.app , but:
>Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate.

**Comment by jrtechs** [comment]
@mbartlet  thanks! I'll add the topic to this repository
